# Generated by Django 5.2.9 on 2026-01-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0002_thing_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
