# Generated by Django 5.2.9 on 2026-01-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0003_thing_posted_at_thing_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='name',
            new_name='Title',
        ),
    ]
