# Generated by Django 5.2.9 on 2026-01-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0004_rename_name_thing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
