# Generated by Django 5.2.9 on 2026-01-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0006_alter_thing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='image',
            new_name='photo',
        ),
    ]
