# Generated by Django 5.2.9 on 2026-01-16 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0008_category_thing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thing.category'),
        ),
    ]
